INSERT INTO Posts (user_id, content, post_type, visibility, like_count, comment_count, share_count, bookmark_count)
VALUES
(1, 'Just started my first blog post on this platform!', 'TEXT', 'PUBLIC', 12, 3, 1, 2),
(2, 'Exploring the beauty of nature in these amazing shots.', 'IMAGE', 'PUBLIC', 24, 6, 4, 5),
(3, 'Excited to announce my upcoming project. Stay tuned!', 'TEXT', 'FRIENDS_ONLY', 45, 8, 7, 10),
(4, 'Check out my latest photography album!', 'IMAGE', 'PRIVATE', 18, 2, 3, 4),
(5, 'Anyone interested in a coding collaboration? DM me.', 'TEXT', 'PUBLIC', 32, 5, 8, 6),
(6, 'Throwback to my favorite moments this year.', 'IMAGE', 'FRIENDS_ONLY', 22, 4, 5, 3),
(7, 'Feeling grateful for all the support recently.', 'TEXT', 'PUBLIC', 40, 7, 9, 8),
(8, 'My artwork collection is finally complete!', 'IMAGE', 'PRIVATE', 16, 3, 2, 1),
(9, 'Sharing my thoughts on the latest tech trends.', 'TEXT', 'FRIENDS_ONLY', 27, 5, 6, 4),
(10, 'This place feels like a dream. Loving it!', 'IMAGE', 'PUBLIC', 34, 8, 7, 9),
(11, 'Starting a new book club. Who’s in?', 'TEXT', 'PUBLIC', 21, 3, 4, 5),
(12, 'Finally completed this sketch. Thoughts?', 'IMAGE', 'FRIENDS_ONLY', 29, 6, 5, 7),
(13, 'Here’s a guide I wrote on personal growth.', 'TEXT', 'PRIVATE', 15, 2, 1, 2),
(14, 'Captured these views on my recent hike.', 'IMAGE', 'PUBLIC', 41, 10, 8, 10),
(15, 'Struggling with some code. Any tips?', 'TEXT', 'FRIENDS_ONLY', 19, 3, 4, 3),
(16, 'Throwing it back to my favorite memories.', 'IMAGE', 'PRIVATE', 12, 1, 2, 2),
(17, 'Sharing my morning thoughts: Stay positive!', 'TEXT', 'PUBLIC', 33, 5, 6, 4),
(18, 'New digital art piece finally done!', 'IMAGE', 'FRIENDS_ONLY', 25, 7, 4, 6),
(19, 'Just published a blog on minimalism. Feedback?', 'TEXT', 'PRIVATE', 17, 4, 3, 3),
(20, 'Snaps from my travel adventures.', 'IMAGE', 'PUBLIC', 36, 9, 7, 8);
