INSERT INTO Users (full_name, username, email, password_hash, bio, account_status, is_verified)
VALUES
('Alice Johnson', 'alice_j', 'alice.j@example.com', 'hashed_password_1', 'Love exploring the outdoors and tech innovations.', 'ACTIVE', TRUE),
('Bob Smith', 'bobbyS', 'b.smith@example.com', 'hashed_password_2', 'Avid gamer and tech enthusiast.', 'ACTIVE', FALSE),
('Catherine Lee', 'cat_lee', 'c.lee@example.com', 'hashed_password_3', 'Passionate about art and coding.', 'ACTIVE', TRUE),
('Daniel Kim', 'dan_kim', 'd.kim@example.com', 'hashed_password_4', 'Full-stack developer and coffee lover.', 'ACTIVE', FALSE),
('Emily Davis', 'emilyD', 'emily.d@example.com', 'hashed_password_5', 'Bookworm and aspiring novelist.', 'ACTIVE', TRUE),
('Frank Moore', 'frankM', 'frank.m@example.com', 'hashed_password_6', 'Music producer and foodie.', 'ACTIVE', FALSE),
('Grace Wilson', 'graceW', 'grace.w@example.com', 'hashed_password_7', 'Health and wellness advocate.', 'ACTIVE', TRUE),
('Henry Brown', 'henryB', 'henry.b@example.com', 'hashed_password_8', 'Tech blogger and traveler.', 'ACTIVE', FALSE),
('Isabella Miller', 'bellaM', 'bella.m@example.com', 'hashed_password_9', 'Fitness coach and motivational speaker.', 'ACTIVE', TRUE),
('James Taylor', 'jamesT', 'james.t@example.com', 'hashed_password_10', 'Data scientist and puzzle solver.', 'ACTIVE', FALSE),
('Karen Walker', 'karenW', 'karen.w@example.com', 'hashed_password_11', 'Photographer with a love for nature.', 'ACTIVE', TRUE),
('Liam Harris', 'liamH', 'liam.h@example.com', 'hashed_password_12', 'AI researcher and chess player.', 'ACTIVE', FALSE),
('Mia Clark', 'miaC', 'mia.c@example.com', 'hashed_password_13', 'Digital artist and tea enthusiast.', 'ACTIVE', TRUE),
('Noah Lewis', 'noahL', 'noah.l@example.com', 'hashed_password_14', 'Entrepreneur and lifelong learner.', 'ACTIVE', FALSE),
('Olivia Allen', 'oliviaA', 'olivia.a@example.com', 'hashed_password_15', 'Traveler and sustainable living advocate.', 'ACTIVE', TRUE),
('Paul Adams', 'paulA', 'paul.a@example.com', 'hashed_password_16', 'Videographer and tech geek.', 'ACTIVE', FALSE),
('Quinn Robinson', 'quinnR', 'quinn.r@example.com', 'hashed_password_17', 'Aspiring filmmaker with a creative edge.', 'ACTIVE', TRUE),
('Rachel Martinez', 'rachelM', 'rachel.m@example.com', 'hashed_password_18', 'Passionate about startups and innovation.', 'ACTIVE', FALSE),
('Sophia Evans', 'sophiaE', 'sophia.e@example.com', 'hashed_password_19', 'Fashion designer and style icon.', 'ACTIVE', TRUE),
('Thomas White', 'thomasW', 'thomas.w@example.com', 'hashed_password_20', 'Tech mentor and community builder.', 'ACTIVE', FALSE);
